[package]
name = "maycoon-core"
description = "Core Functionality for Maycoon UI => See the `maycoon` crate for more."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
winit = "0.30.9"
wgpu-types = "23.0.0"
vello = "0.4.1"
taffy = "0.8.0"
bitflags = "2.9.0"
font-kit = "0.14.2"
futures = { version = "0.3.31", features = ["thread-pool"] }
skrifa = { version = "0.30.0", optional = true }
arc-swap = "1.7.1"
maycoon-theme = { workspace = true }
nalgebra = { workspace = true }
indexmap = { workspace = true }
peniko = { workspace = true }
log = { workspace = true }

[features]
default = ["include-noto-sans"]
include-noto-sans = []

# Re-exports `vello` and `skrifa` for drawing vector graphics.
# Required if you want to make custom widgets or draw vector graphics.
vg = ["skrifa"]
