[package]
name = "maycoon-core"
description = "Core Functionality for Maycoon UI => See the `maycoon` crate for more."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
winit = "0.30.5"
futures-lite = "2.3.0"
wgpu-types = "0.20.0"
vello = "0.2.1"
taffy = "0.5.2"
bitflags = "2.6.0"
font-kit = "0.14.2"
maycoon-theme = { workspace = true }
nalgebra = { workspace = true }
dashmap = { workspace = true }
peniko = { workspace = true }

[features]
default = []

# Re-exports `vello` for drawing vector graphics.
# Required if you want to make custom widgets or draw vector graphics.
vg = []
