[package]
name = "maycoon-core"
description = "Core Functionality for Maycoon UI => See the `maycoon` crate for more."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
winit = "0.30.7"
wgpu-types = "22.0.0"
vello = "0.3.0"
taffy = "0.7.1"
bitflags = "2.6.0"
font-kit = "0.14.2"
futures = { version = "0.3.31", features = ["thread-pool"] }
maycoon-theme = { workspace = true }
nalgebra = { workspace = true }
indexmap = { workspace = true }
peniko = { workspace = true }

[features]
default = []

# Re-exports `vello` for drawing vector graphics.
# Required if you want to make custom widgets or draw vector graphics.
vg = []
