[package]
name = "maycoon-core"
version = "0.1.0"
edition = "2021"
description = "Core Functionality for Maycoon UI => See the `maycoon` crate for more."
readme = "README.md"
license = "MIT OR Apache-2.0"
resolver = "2"
authors = ["Mikail Plotzky <mp@ypon.com>", "Maycoon Contributors"]
categories = ["gui", "graphics", "rendering", "virtualization", "rendering::engine"]
keywords = ["ui", "gui", "interface", "user-interface", "maycoon"]
repository = "https://github.com/maycoon-ui/maycoon"
homepage = "https://maycoon-ui.github.io"

[dependencies]
winit = "0.30.5"
futures-lite = "2.3.0"
wgpu-types = "0.20.0"
vello = "0.2.1"
taffy = "0.5.2"
bitflags = "2.6.0"
maycoon-theme = { path = "../maycoon-theme" }
nalgebra = { workspace = true }
dashmap = { workspace = true }
peniko = { workspace = true }

[features]
default = []

# Re-exports `vello` for drawing vector graphics.
# Required if you want to make custom widgets or draw vector graphics.
vg = []
