// SPDX-License-Identifier: LGPL-3.0-only

//! Color roles for theme colors.
//!
//! These roles represent semantic color purposes that widgets can use
//! to get appropriate colors from the theme.

use std::fmt;

/// Color roles for theme colors.
///
/// These roles represent semantic color purposes that widgets can use
/// to get appropriate colors from the theme.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ColorRole {
    // Window roles
    ActiveWindowBorder1,
    ActiveWindowBorder2,
    ActiveWindowTitle,
    ActiveWindowTitleShadow,
    ActiveWindowTitleStripes,
    InactiveWindowBorder1,
    InactiveWindowBorder2,
    InactiveWindowTitle,
    InactiveWindowTitleShadow,
    InactiveWindowTitleStripes,
    MovingWindowBorder1,
    MovingWindowBorder2,
    MovingWindowTitle,
    MovingWindowTitleShadow,
    MovingWindowTitleStripes,
    HighlightWindowBorder1,
    HighlightWindowBorder2,
    HighlightWindowTitle,
    HighlightWindowTitleShadow,
    HighlightWindowTitleStripes,

    // Widget roles
    Window,
    WindowText,
    Button,
    ButtonText,
    Base,
    BaseText,
    Selection,
    SelectionText,
    InactiveSelection,
    InactiveSelectionText,
    HoverHighlight,
    DisabledTextFront,
    DisabledTextBack,
    PlaceholderText,

    // Menu roles
    MenuBase,
    MenuBaseText,
    MenuSelection,
    MenuSelectionText,
    MenuStripe,

    // Link roles
    Link,
    ActiveLink,
    VisitedLink,

    // Syntax highlighting roles
    SyntaxComment,
    SyntaxKeyword,
    SyntaxControlKeyword,
    SyntaxString,
    SyntaxNumber,
    SyntaxType,
    SyntaxIdentifier,
    SyntaxFunction,
    SyntaxVariable,
    SyntaxCustomType,
    SyntaxNamespace,
    SyntaxMember,
    SyntaxParameter,
    SyntaxPreprocessorStatement,
    SyntaxPreprocessorValue,
    SyntaxPunctuation,
    SyntaxOperator,

    // Terminal colors
    Black,
    Red,
    Green,
    Yellow,
    Blue,
    Magenta,
    Cyan,
    White,
    BrightBlack,
    BrightRed,
    BrightGreen,
    BrightYellow,
    BrightBlue,
    BrightMagenta,
    BrightCyan,
    BrightWhite,
    ColorSchemeBackground,
    ColorSchemeForeground,

    // Other roles
    Accent,
    DesktopBackground,
    FocusOutline,
    TextCursor,
    ThreedHighlight,
    ThreedShadow1,
    ThreedShadow2,
    RubberBandFill,
    RubberBandBorder,
    Gutter,
    GutterBorder,
    Ruler,
    RulerBorder,
    RulerActiveText,
    RulerInactiveText,
    Tooltip,
    TooltipText,
    Tray,
    TrayText,
    OverlayBackground,
    OverlayText,
    HighlightSearching,
    HighlightSearchingText,
}

crate::impl_role_string_conversion!(ColorRole, {
    ActiveWindowBorder1 => "ActiveWindowBorder1",
    ActiveWindowBorder2 => "ActiveWindowBorder2",
    ActiveWindowTitle => "ActiveWindowTitle",
    ActiveWindowTitleShadow => "ActiveWindowTitleShadow",
    ActiveWindowTitleStripes => "ActiveWindowTitleStripes",
    InactiveWindowBorder1 => "InactiveWindowBorder1",
    InactiveWindowBorder2 => "InactiveWindowBorder2",
    InactiveWindowTitle => "InactiveWindowTitle",
    InactiveWindowTitleShadow => "InactiveWindowTitleShadow",
    InactiveWindowTitleStripes => "InactiveWindowTitleStripes",
    MovingWindowBorder1 => "MovingWindowBorder1",
    MovingWindowBorder2 => "MovingWindowBorder2",
    MovingWindowTitle => "MovingWindowTitle",
    MovingWindowTitleShadow => "MovingWindowTitleShadow",
    MovingWindowTitleStripes => "MovingWindowTitleStripes",
    HighlightWindowBorder1 => "HighlightWindowBorder1",
    HighlightWindowBorder2 => "HighlightWindowBorder2",
    HighlightWindowTitle => "HighlightWindowTitle",
    HighlightWindowTitleShadow => "HighlightWindowTitleShadow",
    HighlightWindowTitleStripes => "HighlightWindowTitleStripes",
    Window => "Window",
    WindowText => "WindowText",
    Button => "Button",
    ButtonText => "ButtonText",
    Base => "Base",
    BaseText => "BaseText",
    Selection => "Selection",
    SelectionText => "SelectionText",
    InactiveSelection => "InactiveSelection",
    InactiveSelectionText => "InactiveSelectionText",
    HoverHighlight => "HoverHighlight",
    DisabledTextFront => "DisabledTextFront",
    DisabledTextBack => "DisabledTextBack",
    PlaceholderText => "PlaceholderText",
    MenuBase => "MenuBase",
    MenuBaseText => "MenuBaseText",
    MenuSelection => "MenuSelection",
    MenuSelectionText => "MenuSelectionText",
    MenuStripe => "MenuStripe",
    Link => "Link",
    ActiveLink => "ActiveLink",
    VisitedLink => "VisitedLink",
    SyntaxComment => "SyntaxComment",
    SyntaxKeyword => "SyntaxKeyword",
    SyntaxControlKeyword => "SyntaxControlKeyword",
    SyntaxString => "SyntaxString",
    SyntaxNumber => "SyntaxNumber",
    SyntaxType => "SyntaxType",
    SyntaxIdentifier => "SyntaxIdentifier",
    SyntaxFunction => "SyntaxFunction",
    SyntaxVariable => "SyntaxVariable",
    SyntaxCustomType => "SyntaxCustomType",
    SyntaxNamespace => "SyntaxNamespace",
    SyntaxMember => "SyntaxMember",
    SyntaxParameter => "SyntaxParameter",
    SyntaxPreprocessorStatement => "SyntaxPreprocessorStatement",
    SyntaxPreprocessorValue => "SyntaxPreprocessorValue",
    SyntaxPunctuation => "SyntaxPunctuation",
    SyntaxOperator => "SyntaxOperator",
    Black => "Black",
    Red => "Red",
    Green => "Green",
    Yellow => "Yellow",
    Blue => "Blue",
    Magenta => "Magenta",
    Cyan => "Cyan",
    White => "White",
    BrightBlack => "BrightBlack",
    BrightRed => "BrightRed",
    BrightGreen => "BrightGreen",
    BrightYellow => "BrightYellow",
    BrightBlue => "BrightBlue",
    BrightMagenta => "BrightMagenta",
    BrightCyan => "BrightCyan",
    BrightWhite => "BrightWhite",
    ColorSchemeBackground => "ColorSchemeBackground",
    ColorSchemeForeground => "ColorSchemeForeground",
    Accent => "Accent",
    DesktopBackground => "DesktopBackground",
    FocusOutline => "FocusOutline",
    TextCursor => "TextCursor",
    ThreedHighlight => "ThreedHighlight",
    ThreedShadow1 => "ThreedShadow1",
    ThreedShadow2 => "ThreedShadow2",
    RubberBandFill => "RubberBandFill",
    RubberBandBorder => "RubberBandBorder",
    Gutter => "Gutter",
    GutterBorder => "GutterBorder",
    Ruler => "Ruler",
    RulerBorder => "RulerBorder",
    RulerActiveText => "RulerActiveText",
    RulerInactiveText => "RulerInactiveText",
    Tooltip => "Tooltip",
    TooltipText => "TooltipText",
    Tray => "Tray",
    TrayText => "TrayText",
    OverlayBackground => "OverlayBackground",
    OverlayText => "OverlayText",
    HighlightSearching => "HighlightSearching",
    HighlightSearchingText => "HighlightSearchingText",
});

impl fmt::Display for ColorRole {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
