[package]
name = "maycoon-macros"
description = "Macros for Maycoon UI => See the `maycoon` crate for more."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
maycoon-core = { workspace = true }
syn = "2.0.76"
quote = "1.0.37"
proc-macro2 = "1.0.86"

[lib]
proc-macro = true
